### ISSUE TITLE
[Bug]: no such attribute 'stamp' in 'py_test' rule

### ISSUE THREAD

**Issue by jamison-lahman-ai** [aspect-build/rules_py#161]
### What happened?

Support for `py_test.stamp`, https://bazel.build/reference/be/python#py_test.stamp

```
$ bazel test //examples/py:py_test 
ERROR: /home/jamison/code/rules_py/examples/py/BUILD.bazel:3:8: //examples/py:py_test: no such attribute 'stamp' in 'py_test' rule
ERROR: error loading package 'examples/py': Package 'examples/py' contains errors
INFO: Elapsed time: 0.095s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
FAILED: Build did NOT complete successfully (0 packages loaded)

```

### Version

Development (host) and target OS/architectures:

Output of `bazel --version`:

`bazel 5.4.0`

Version of the Aspect rules, or other relevant rules from your
`WORKSPACE` or `MODULE.bazel` file:

local rules_py workspace, HEAD

### How to reproduce

https://github.com/jl-applied/rules_py/tree/jamison/161,

```shell
bazel test //examples/py:py_test
```

**Comment by alexeagle** [comment]
Interesting, is there a use case for setting a `stamp` attribute on a test target? I think in theory we want to support the full `py_*` native rule API to make migrations easy, but this one feels more like a bug than a feature to me.

**Comment by jl-applied** [comment]
We explicitly default to `stamp = false` in a macro for our `py_*` rules. I suspect with a small refactor + slight code duplication at worse, we could workaround this without needing this attribute on any of our `py_test`s.

This was the first snag I hit when trying to migrate and was enough to get the migration shelved, so figured I'd open a ticket. Disallowing `stamp` seems reasonable to me, though an explicit comment stating this is intentional would be nice.

**Comment by alexeagle** [comment]
Our macro can have a `stamp` attribute, but we just error when you pass it so you get the documentation in the right spot.

**Comment by alexeagle** [comment]
Sorry, a year later we didn't have any time for this. I think it's an obscure corner case to expect a test target to have a `stamp` attribute, it's really a rules_python bug?
