### ISSUE TITLE
non-wheel external dependencies don't make it into the IDE venv

### ISSUE THREAD

**Issue by mattem** [aspect-build/rules_py#31]
If there is a dependency on an external `py_library` that isn't consumed via the `py_wheel` rule, eg it's a `py_library` generated by rules_python for a pip install, and referenced via the `:pkg` label, then when a venv is created for the test or binary target for IDE consumption, the dependency is missing from the venv, as the `.pth` file points to the path in the runfiles tree.

**Comment by psalvaggio-dl** [comment]
I have been able to verify this bug. For my use case, this is important because we rely on virtual environments for people's development environments and running some command line tools that have proven difficult to integrate into Bazel due to other bugs or missing features. In order to migrate a monorepo onto these rules, I would need to ensure that all of my dependencies were wheel dependencies, which requires explicitly annotating them in the `pip_parse` call. Since Starlark can't read files and you can't subclass `dict()`, there's not a clean way to do this with a traditional `requirements.txt` file.

**Comment by alexeagle** [comment]
Maybe already fixed...

**Comment by mattem** [comment]
Fixed by https://github.com/aspect-build/rules_py/pull/233
